### ISSUE TITLE
Default Configure Could Cause Container Escape Risk

### ISSUE THREAD

**Issue by OrangeGzY** [tinyclub/linux-lab#14]
Greetings!

This is security research team from Tsinghua University, in recent research work, we found that linux-lab(one of the best cloudlabs) could be escaped by default configure. We do think it may somehow affect the project itself and users who build their own labs based-on linux-lab. Also, we will propose our practical mitigation suggestion : )

We have sent serveral e-mails about the security issues, including the escaping video record. We would appreciate if you can check the information in the e-mails we sent.

Sincerely,

**Comment by lzufalcon** [comment]
Thanks for your report, this issue will be sovled in next release.

**Comment by OrangeGzY** [comment]
Thanks for your efforts to solve it.
