### ISSUE TITLE
x86版本的uboot可以编译作为mbr引导启动吗？

### ISSUE THREAD

**Issue by iDalink** [tinyclub/linux-lab#2]
我发现uboot在x86目标山编译之后是作为coreboot的payload启动，我能把他作为mbr的引导启动吗？

If you cannt read previous words, I should use English.

**Comment by lzufalcon** [comment]
理论上应该是可以的，但是需要确保 uboot 能够在 MBR 的前 512 个字节放得下吧，如果要在 X86 上研究 Uboot，建议用 -kernel 的方式，先启动 Uboot，再让 Uboot 通过 tftp 或者磁盘加载的方式把内核和 rootfs load 进来。

如果只是为了研究 Uboot ，建议用 arm/versatilepb 和 arm/vexpress-a9，这两款现在都是支持 Uboot 引导的。Linux Lab 默认已经支持了，`make boot B=arm/versatilepb`

**Comment by iDalink** [comment]
我想用它在真机上来引导我的Arch Linux，并取代grub。
Readme.efi文档中描述了把uboot编译为efi app的方法。这个可以尝试下，虽然这方法不是我最开始的mbr方式。
我继续研究下。
