### ISSUE TITLE
Docker cannot run successfully.

### ISSUE THREAD

**Issue by hjw21century** [tinyclub/linux-lab#3]
failed to register layer: Error processing tar file(exit status 1): function not implemented
LOG: pulling git repo: linux-lab
LOG: Current Lab is linux-lab
xrandr: Failed to get size of gamma for output default
LOG: pulling repository: linux-lab

**Comment by lzufalcon** [comment]
@hjw21century which host system are you using? could you please add our wechat: tinylab and discuss for more details.

**Comment by hjw21century** [comment]
macOS High Sierra

**Comment by lzufalcon** [comment]
@hjw21century sorry, I have no macOS environment at hand currently.

**Comment by lzufalcon** [comment]
@hjw21century Add xrandr running check, It should fix up this issue, close it.
