### ISSUE TITLE
一直wait launching 进去不

### ISSUE THREAD

**Issue by luyahan** [tinyclub/linux-lab#4]
![image](https://user-images.githubusercontent.com/22358871/77844209-320f6b00-71d7-11ea-94be-325ccc8b7809.png)
![image](https://user-images.githubusercontent.com/22358871/77844213-38054c00-71d7-11ea-9837-9cc600f27cd4.png)

一直wait launching 进去不

**Comment by luyahan** [comment]
docker 版本 2.2.04

**Comment by lzufalcon** [comment]
@luyahan 加微信 tinylab 到用户群沟通哈。需要确认下更多信息，比如系统，docker ps -a以及 docker logs linux-lab。
