### ISSUE TITLE
OCI runtime exec failed: exec failed

### ISSUE THREAD

**Issue by waruqi** [tinyclub/linux-lab#6]
首次尝试登入进去后，不知道怎么退出，就执行了poweroff，然后终端还是没退出shell，所以强关了终端，之后第二次进去就报错了。。

```
$ ./tools/docker/run linux-lab
LOG: Open the running linux-lab
LOG: Available login methods:

     bash vnc ssh webssh webvnc

LOG: Switch to another method:

     tools/docker/login LOGIN_METHOD

LOG: Running 'tools/docker/bash'

OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "chdir to cwd (\"//labs/linux-lab\") set in config.json failed: no such file or directory": unknown
```

**Comment by lzufalcon** [comment]
@waruqi hello，加一下微信号 tinylab 进用户讨论群哈。可以重新运行一下试试：

```
$ tools/docker/rerun linux-lab
```

是退出 qemu 还是什么呢？退出 qemu 有 CTRL+A x。
退出 bash 的话，执行 exit。

**Comment by waruqi** [comment]
执行rerun后，可以重新进去了

应该是qemu退出吧，我执行CTRL+A，就退到`linux-lab login:`  然后就一直卡在login，要么重新登录，就是没法退出

微信提交申请了

**Comment by lzufalcon** [comment]
@waruqi 文档 FAQ  有介绍怎么退出的，很多方法。

**Comment by lzufalcon** [comment]
@waruqi https://gitee.com/tinylab/linux-lab#623-%E5%A6%82%E4%BD%95%E9%80%80%E5%87%BA-qemu

**Comment by waruqi** [comment]
串口控制台 | CTRL+a x
基于 Curses 的图形终端 | ESC+2 quit 或 ALT+2 quit
基于 X 图形终端 | CTRL+ALT+2 quit
通用方法 | poweroff, reboot, kill, pkill

我这是mac的终端，前三种似乎没啥反应

执行poweroff 最后os退了 终端还是没法完全退出到 正常的 主机shell

![image](https://user-images.githubusercontent.com/151335/89310336-219c5f00-d6a7-11ea-9cb4-6d540438ff00.png)

**Comment by waruqi** [comment]
基于 X 图形终端 | CTRL+ALT+2 quit

这个可以了，非常感谢
