### ISSUE TITLE
Makefile:31: *** ERR: Please not try Linux Lab in local host, but use it with Cloud Lab, please refer to 'Run and login the lab' part of README.md.  Stop.

### ISSUE THREAD

**Issue by pzh2386034** [tinyclub/linux-lab#7]
刚接触linux-lab，操作比较陌生；安装README.md的步骤，在Quickstart: Boot a board，部分
cd labs/linux-lab
make boot
一直报上面的错误，不知道如何处理，请教下大家

**Comment by lzufalcon** [comment]
@pzh2386034 加一下微信号 tinylab 进讨论群哦，目前 Linux Lab 是禁止直接在 host 使用的，需要通过 Cloud Lab 使用，文档已经详细说明了。

记得先切到普通用户权限：

git clone https://gitee.com/tinylab/cloud-lab
cd cloud-lab
tools/docker/run linux-lab

**Comment by pzh2386034** [comment]
嗯，谢谢；确实，刚开始用没理解
