### ISSUE TITLE
*** Your GCC is older than 6.0 and is not supported

### ISSUE THREAD

**Issue by pzh2386034** [tinyclub/linux-lab#8]
在cloud中执行 
make uboot 失败，报错如上
但是查看gcc版本是8.3.0的，是什么原因有人碰到过吗？
env PATH=/labs/linux-lab/prebuilt/toolchains/arm/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin  make O=/labs/linux-lab/output/arm/uboot-v2020.04-vexpress-a9 -C u-boot ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -j8
make[1]: Entering directory `/labs/linux-lab/u-boot'
make[2]: Entering directory `/labs/linux-lab/output/arm/uboot-v2020.04-vexpress-a9'
  CHK     include/config/uboot.release
  CHK     include/generated/timestamp_autogenerated.h
  GEN     ./Makefile
  UPD     include/generated/timestamp_autogenerated.h
*** Your GCC is older than 6.0 and is not supported
make[2]: *** [checkgcc6] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory `/labs/linux-lab/u-boot'
make: *** [_uboot] Error 2
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
##gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-16ubuntu3~14.04.2' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-16ubuntu3~14.04.2)

**Comment by lzufalcon** [comment]
@pzh2386034 加微信 tinylab 进用户群沟通哈，可能是用了别的板子后编译器切回了老版本，需要再确认一下。

**Comment by lzufalcon** [comment]
@pzh2386034 在新版的 v0.5-rc2 确实有个 bug，你可以切换到 v0.4 或者切换到 next 分支并更新（刚已经在该分支修复）来使用。

例如：

    git checkout v0.4

或

    git checkout next
    git pull

**Comment by lzufalcon** [comment]
v0.5-rc3 已经修复。

**Comment by lzufalcon** [comment]
v0.5-rc3 已经修复。
