### ISSUE TITLE
能不能只使用 linux-lab 容器，web 功能暂时用不上, cloud-ubuntu-web 太大了...

### ISSUE THREAD

**Issue by luoshenzhi** [tinyclub/linux-lab#9]

**Comment by lzufalcon** [comment]
@luoshenzhi 可以的，不用 webvnc 的话，可以关闭 cloud-ubuntu-web。其实也不是很大，才 500 多 M。

**Comment by lzufalcon** [comment]
@luoshenzhi 后面我们搞一个版本，默认关闭该功能吧。多谢反馈和建议。可以加 tinylab 微信进用户群哈。
